"""Builds ASAP2-compliant A2L file from parsed ELF and MAP data for CANoe import."""

from __future__ import annotations

import os
import re
from datetime import datetime

# ASAP2 datatype name mapping from internal ELF-parser types
_DATATYPE_MAP: dict[str, str] = {
    'UBYTE':        'UBYTE',
    'BYTE':         'SBYTE',
    'UWORD':        'UWORD',
    'WORD':         'SWORD',
    'ULONG':        'ULONG',
    'LONG':         'SLONG',
    'FLOAT32_IEEE': 'FLOAT32_IEEE',
    'FLOAT64_IEEE': 'FLOAT64_IEEE',
}

# Default physical limits per ASAP2 datatype
_TYPE_LIMITS: dict[str, tuple[float, float]] = {
    'UBYTE':        (0,              255),
    'SBYTE':        (-128,           127),
    'UWORD':        (0,              65535),
    'SWORD':        (-32768,         32767),
    'ULONG':        (0,              4294967295),
    'SLONG':        (-2147483648,    2147483647),
    'FLOAT32_IEEE': (-3.4028235e38,  3.4028235e38),
    'FLOAT64_IEEE': (-1.7976931e308, 1.7976931e308),
}

# Size in bytes per ASAP2 datatype
_TYPE_SIZE: dict[str, int] = {
    'UBYTE': 1, 'SBYTE': 1,
    'UWORD': 2, 'SWORD': 2,
    'ULONG': 4, 'SLONG': 4,
    'FLOAT32_IEEE': 4, 'FLOAT64_IEEE': 8,
}

# Scalar RECORD_LAYOUT name per ASAP2 datatype (referenced by CHARACTERISTIC)
_RECORD_LAYOUT: dict[str, str] = {
    'UBYTE':        'RL_UBYTE_VALUE',
    'SBYTE':        'RL_SBYTE_VALUE',
    'UWORD':        'RL_UWORD_VALUE',
    'SWORD':        'RL_SWORD_VALUE',
    'ULONG':        'RL_ULONG_VALUE',
    'SLONG':        'RL_SLONG_VALUE',
    'FLOAT32_IEEE': 'RL_FLOAT32_VALUE',
    'FLOAT64_IEEE': 'RL_FLOAT64_VALUE',
}

# ASAP2 FORMAT strings must be "%<total length>.<decimal places>"
_TYPE_FORMAT: dict[str, str] = {
    'UBYTE': '%3.0', 'SBYTE': '%4.0',
    'UWORD': '%5.0', 'SWORD': '%6.0',
    'ULONG': '%10.0', 'SLONG': '%11.0',
    'FLOAT32_IEEE': '%15.6', 'FLOAT64_IEEE': '%20.9',
}

# Characters allowed in an ASAP2 1.6 identifier
_IDENT_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_.\[\]]*$')


def generate_a2l(elf_data, map_data, output_path, template_path=None, selected_symbols=None,
                 advanced_mode=False,
                 xcp_request_id=None, xcp_response_id=None, access='Read only'):
    """Generate industry-standard A2L file with MEASUREMENT and CHARACTERISTIC definitions.

    selected_symbols may be a sequence of names or a {name: 'r'|'rw'} mapping that
    overrides the global access setting per variable.
    """

    map_data = map_data or {}
    default_access = 'rw' if str(access).lower().startswith('read and') or str(access).lower().startswith('read/') else 'r'

    if isinstance(selected_symbols, dict):
        access_map = dict(selected_symbols)
        candidates = list(selected_symbols.keys())
    else:
        # The ELF symbol table is authoritative; statics are absent from most MAP files
        candidates = list(selected_symbols) if selected_symbols is not None else sorted(elf_data.keys())
        access_map = {}

    selected_symbols = [
        s for s in candidates
        if s in elf_data and s != '_enums' and elf_data[s].get('size', 0) > 0
        and _IDENT_RE.match(s)
    ]
    # Duplicate object names make CANoe discard the whole module
    selected_symbols = sorted(dict.fromkeys(selected_symbols))
    access_map = {s: access_map.get(s, default_access) for s in selected_symbols}
    writable = [s for s in selected_symbols if access_map[s] == 'rw']

    enums = elf_data.get('_enums', {})

    used_types = sorted({_to_a2l_datatype(elf_data[s].get('datatype', 'UBYTE')) for s in selected_symbols})

    lines: list[str] = []
    lines.append('ASAP2_VERSION 1 61')
    lines.append('')
    lines.append('/begin PROJECT A2LGenerator "A2L File generated by A2L Generator"')
    lines.append('')
    lines.append('  /begin HEADER "A2L Generator Output"')
    lines.append(f'    VERSION "{datetime.now().strftime("%Y-%m-%d")}"')
    lines.append('    PROJECT_NO A2LGEN001')
    lines.append('  /end HEADER')
    lines.append('')
    lines.append('  /begin MODULE A2LModule "Auto-generated Module"')
    lines.append('')
    lines.append('    /begin MOD_PAR "Generated from ELF and MAP"')
    lines.append('    /end MOD_PAR')
    lines.append('')
    # TriCore/HighTec targets are little endian
    lines.append('    /begin MOD_COMMON "Common parameters"')
    lines.append('      BYTE_ORDER MSB_LAST')
    lines.append('      ALIGNMENT_BYTE 1')
    lines.append('      ALIGNMENT_WORD 2')
    lines.append('      ALIGNMENT_LONG 4')
    lines.append('      ALIGNMENT_FLOAT32_IEEE 4')
    lines.append('      ALIGNMENT_FLOAT64_IEEE 8')
    lines.append('      DEPOSIT ABSOLUTE')
    lines.append('    /end MOD_COMMON')
    lines.append('')

    lines.extend(_build_xcp_if_data(xcp_request_id, xcp_response_id))
    lines.extend(_build_record_layouts(used_types))
    lines.extend(_build_compu_methods(elf_data, selected_symbols))
    lines.extend(_build_measurements(elf_data, map_data, selected_symbols, access_map))

    if writable:
        lines.extend(_build_characteristics(elf_data, map_data, writable, enums))

    lines.append('  /end MODULE')
    lines.append('')
    lines.append('/end PROJECT')

    body_text = '\n'.join(lines) + '\n'

    if template_path and os.path.exists(template_path):
        with open(template_path, 'r', encoding='utf-8') as f:
            template = f.read()
        if '{{A2L_BODY}}' in template:
            final_text = template.replace('{{A2L_BODY}}', body_text)
        elif '{A2L_BODY}' in template:
            final_text = template.replace('{A2L_BODY}', body_text)
        else:
            final_text = _merge_template_variable_tail(template, body_text)
    else:
        final_text = body_text

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(final_text)


def _merge_template_variable_tail(template: str, generated_body: str) -> str:
    """Keep template configuration and replace its module variable-data tail."""
    generated_lines = generated_body.splitlines()
    module_end = _find_line(generated_lines, r'^\s*/end MODULE\s*$')
    if module_end is None:
        return generated_body

    variable_start = _find_line(
        generated_lines,
        r'^\s*/begin (?:RECORD_LAYOUT|COMPU_METHOD|MEASUREMENT|CHARACTERISTIC)\b',
    )
    if variable_start is None:
        variable_lines: list[str] = []
    else:
        variable_lines = generated_lines[variable_start:module_end]

    template_lines = template.splitlines()
    template_module_end = _find_line(template_lines, r'^\s*/end MODULE\s*$')
    if template_module_end is None:
        return template.rstrip() + '\n\n' + '\n'.join(variable_lines) + '\n'

    # Prefer the last IF_DATA block because module configuration can contain several.
    if_data_end = _find_last_line(template_lines, r'^\s*/end IF_DATA\s*$')
    if if_data_end is None:
        variable_tail_start = _find_line(
            template_lines,
            r'^\s*/begin (?:RECORD_LAYOUT|COMPU_METHOD|MEASUREMENT|CHARACTERISTIC)\b',
        )
        if variable_tail_start is None or variable_tail_start > template_module_end:
            variable_tail_start = template_module_end
    else:
        variable_tail_start = if_data_end + 1

    prefix = '\n'.join(template_lines[:variable_tail_start]).rstrip()
    suffix = '\n'.join(template_lines[template_module_end:]).lstrip()
    parts = [prefix]
    if variable_lines:
        parts.append('\n'.join(variable_lines).strip())
    parts.append(suffix)
    return '\n\n'.join(part for part in parts if part) + '\n'


def _find_line(lines: list[str], pattern: str) -> int | None:
    """Return the first line matching a regular expression."""
    matcher = re.compile(pattern, re.IGNORECASE)
    for index, line in enumerate(lines):
        if matcher.match(line):
            return index
    return None


def _find_last_line(lines: list[str], pattern: str) -> int | None:
    """Return the last line matching a regular expression."""
    matcher = re.compile(pattern, re.IGNORECASE)
    matches = [index for index, line in enumerate(lines) if matcher.match(line)]
    return matches[-1] if matches else None


_XCP_PROTOCOL_LAYER = [
    '      /begin PROTOCOL_LAYER',
    '        0x0100',
    '        0x03E8',
    '        0x0BB8',
    '        0x00',
    '        0x00',
    '        0x00',
    '        0x00',
    '        0x00',
    '        0x08',
    '        0x08',
    '        BYTE_ORDER_MSB_LAST',
    '        ADDRESS_GRANULARITY_BYTE',
    '        OPTIONAL_CMD GET_COMM_MODE_INFO',
    '        OPTIONAL_CMD GET_ID',
    '        OPTIONAL_CMD SET_MTA',
    '        OPTIONAL_CMD UPLOAD',
    '        OPTIONAL_CMD SHORT_UPLOAD',
    '        OPTIONAL_CMD DOWNLOAD',
    '        OPTIONAL_CMD SHORT_DOWNLOAD',
    '        OPTIONAL_CMD CLEAR_DAQ_LIST',
    '        OPTIONAL_CMD SET_DAQ_PTR',
    '        OPTIONAL_CMD WRITE_DAQ',
    '        OPTIONAL_CMD SET_DAQ_LIST_MODE',
    '        OPTIONAL_CMD GET_DAQ_LIST_MODE',
    '        OPTIONAL_CMD START_STOP_DAQ_LIST',
    '        OPTIONAL_CMD START_STOP_SYNCH',
    '        OPTIONAL_CMD GET_DAQ_PROCESSOR_INFO',
    '        OPTIONAL_CMD GET_DAQ_RESOLUTION_INFO',
    '        OPTIONAL_CMD FREE_DAQ',
    '        OPTIONAL_CMD ALLOC_DAQ',
    '        OPTIONAL_CMD ALLOC_ODT',
    '        OPTIONAL_CMD ALLOC_ODT_ENTRY',
    '      /end PROTOCOL_LAYER',
]

_XCP_DAQ = [
    '      /begin DAQ',
    '        DYNAMIC',
    '        0x00',
    '        0x01',
    '        0x00',
    '        OPTIMISATION_TYPE_DEFAULT',
    '        ADDRESS_EXTENSION_FREE',
    '        IDENTIFICATION_FIELD_TYPE_ABSOLUTE',
    '        GRANULARITY_ODT_ENTRY_SIZE_DAQ_BYTE',
    '        0x07',
    '        OVERLOAD_INDICATION_PID',
    '        /begin EVENT',
    '          "10 ms"',
    '          "10ms"',
    '          0x01',
    '          DAQ',
    '          0xFF',
    '          0x0A',
    '          0x06',
    '          0x00',
    '        /end EVENT',
    '      /end DAQ',
]


def _build_xcp_if_data(request_id, response_id) -> list[str]:
    """Emit the XCP-on-CAN interface block CANoe needs in order to talk to the slave."""
    if request_id is None or response_id is None:
        return []

    lines = ['    /begin IF_DATA XCP']
    lines.extend(_XCP_PROTOCOL_LAYER)
    lines.extend(_XCP_DAQ)
    lines.append('      /begin XCP_ON_CAN')
    lines.append('        0x0100')
    lines.append(f'        CAN_ID_MASTER 0x{_can_id(request_id):08X}')
    lines.append(f'        CAN_ID_SLAVE 0x{_can_id(response_id):08X}')
    lines.append('        BAUDRATE 0x0007A120')
    lines.append('        MAX_DLC_REQUIRED')
    lines.append('      /end XCP_ON_CAN')
    lines.append('    /end IF_DATA')
    lines.append('')
    return lines


def _can_id(value) -> int:
    """Return the XCP identifier exactly as supplied by the ECU configuration."""
    ident = int(value)
    if ident < 0 or ident > 0xFFFFFFFF:
        raise ValueError(f"XCP CAN ID is outside the 32-bit range: {value}")
    return ident


def _build_record_layouts(used_types) -> list[str]:
    """Emit one scalar RECORD_LAYOUT per datatype; every CHARACTERISTIC must reference one."""
    lines: list[str] = []
    for a2l_type in used_types:
        rl_name = _RECORD_LAYOUT.get(a2l_type)
        if not rl_name:
            continue
        lines.append(f'    /begin RECORD_LAYOUT {rl_name}')
        lines.append(f'      FNC_VALUES 1 {a2l_type} ROW_DIR DIRECT')
        lines.append('    /end RECORD_LAYOUT')
        lines.append('')
    return lines


def _build_compu_methods(elf_data, selected_symbols) -> list[str]:
    """Emit a LINEAR conversion per scaled symbol; unscaled symbols use NO_COMPU_METHOD."""
    lines: list[str] = []

    added: set[str] = set()
    for symbol in selected_symbols:
        scaling = elf_data.get(symbol, {}).get('scaling', 1.0)
        if not scaling or scaling == 1.0:
            continue
        name = f'CM_{symbol}'
        if name in added:
            continue
        # LINEAR takes COEFFS_LINEAR a b with phys = a*raw + b
        lines.append(f'    /begin COMPU_METHOD {name} "Scaling for {symbol}" LINEAR "%15.6" ""')
        lines.append(f'      COEFFS_LINEAR {scaling} 0')
        lines.append('    /end COMPU_METHOD')
        lines.append('')
        added.add(name)

    return lines


def _build_measurements(elf_data, map_data, selected_symbols, access_map=None) -> list[str]:
    """Build one MEASUREMENT block per symbol using ASAP2 positional-arg syntax."""
    lines: list[str] = []
    access_map = access_map or {}

    for symbol in selected_symbols:
        elf_info = elf_data[symbol]
        map_info = map_data.get(symbol, {})

        address  = elf_info.get('address') or map_info.get('address', 0)
        raw_type = elf_info.get('datatype', 'UBYTE')
        scaling  = elf_info.get('scaling', 1.0)
        link     = elf_info.get('symbol', symbol)

        a2l_type     = _to_a2l_datatype(raw_type)
        lower, upper = _TYPE_LIMITS.get(a2l_type, (0, 255))
        bit_size = elf_info.get('bit_size')
        if bit_size:
            upper = (1 << bit_size) - 1
        if scaling and scaling != 1.0:
            compu_method = f'CM_{symbol}'
            # Limits are physical values, so they follow the conversion
            lower, upper = sorted((lower * scaling, upper * scaling))
        else:
            compu_method = 'NO_COMPU_METHOD'

        # ASAP2 MEASUREMENT: name longIdentifier dataType conversion resolution accuracy lowerLimit upperLimit
        lines.append(f'    /begin MEASUREMENT {symbol} "{symbol}"')
        lines.append(f'      {a2l_type} {compu_method} 0 0 {_num(lower)} {_num(upper)}')
        lines.append(f'      ECU_ADDRESS 0x{address:08X}')
        lines.append('      ECU_ADDRESS_EXTENSION 0x0')
        lines.append(f'      FORMAT "{_TYPE_FORMAT.get(a2l_type, "%10.0")}"')
        lines.append(f'      SYMBOL_LINK "{link}" 0')
        if bit_size and elf_info.get('bit_mask') is not None:
            lines.append(f'      BIT_MASK 0x{elf_info["bit_mask"]:X}')
        if access_map.get(symbol) == 'rw':
            lines.append('      READ_WRITE')
        elements = _element_count(elf_info.get('size', 0), a2l_type)
        if elements > 1:
            lines.append(f'      MATRIX_DIM {elements} 1 1')
        lines.append('    /end MEASUREMENT')
        lines.append('')

    return lines


def _build_characteristics(elf_data, map_data, selected_symbols, enums) -> list[str]:
    """Build one CHARACTERISTIC block per symbol (advanced mode)."""
    lines: list[str] = []

    for symbol in selected_symbols:
        elf_info = elf_data[symbol]
        map_info = map_data.get(symbol, {})

        address  = elf_info.get('address') or map_info.get('address', 0)
        raw_type = elf_info.get('datatype', 'UBYTE')
        link     = elf_info.get('symbol', symbol)

        a2l_type     = _to_a2l_datatype(raw_type)
        lower, upper = _TYPE_LIMITS.get(a2l_type, (0, 255))
        bit_size = elf_info.get('bit_size')
        if bit_size:
            upper = (1 << bit_size) - 1
        rl_name      = _RECORD_LAYOUT.get(a2l_type, 'RL_UBYTE_VALUE')

        # ASAP2 CHARACTERISTIC: name longIdentifier type address recordLayout maxDiff conversion lowerLimit upperLimit
        # Prefixed name keeps the CHARACTERISTIC unique against the MEASUREMENT of the same symbol
        lines.append(f'    /begin CHARACTERISTIC C_{symbol} "{symbol}"')
        lines.append(f'      VALUE 0x{address:08X} {rl_name} 0 NO_COMPU_METHOD {_num(lower)} {_num(upper)}')
        lines.append(f'      FORMAT "{_TYPE_FORMAT.get(a2l_type, "%10.0")}"')
        lines.append(f'      SYMBOL_LINK "{link}" 0')
        if bit_size and elf_info.get('bit_mask') is not None:
            lines.append(f'      BIT_MASK 0x{elf_info["bit_mask"]:X}')
        lines.append('    /end CHARACTERISTIC')
        lines.append('')

    return lines


def _element_count(size: int, a2l_type: str) -> int:
    """Number of datatype elements the symbol spans; 1 for scalars."""
    elem = _TYPE_SIZE.get(a2l_type, 1)
    if size and elem and size % elem == 0:
        return size // elem
    return 1


def _num(value: float) -> str:
    """Render a limit as an integer when possible, otherwise in ASAP2-safe exponent notation."""
    if float(value).is_integer() and abs(value) < 1e15:
        return str(int(value))
    return repr(float(value)).upper()


def _to_a2l_datatype(dtype: str) -> str:
    """Map internal ELF-parser type name to ASAP2 datatype keyword."""
    return _DATATYPE_MAP.get(dtype, 'UBYTE')
