"""Builds ASAP2-compliant A2L file from parsed ELF and MAP data for CANoe import."""

import os
from datetime import datetime


def generate_a2l(elf_data, map_data, output_path, template_path=None, selected_symbols=None, advanced_mode=False):
    """Generate industry-standard A2L file with MEASUREMENT and CHARACTERISTIC definitions."""
    
    # Filter symbols that exist in both ELF and MAP
    selected_symbols = selected_symbols if selected_symbols is not None else sorted(map_data.keys())
    selected_symbols = [s for s in selected_symbols if s in map_data and s in elf_data and s != '_enums']
    
    # Extract enums if available
    enums = elf_data.get('_enums', {})
    
    # Build A2L content
    lines = []
    lines.append('/begin PROJECT A2LGenerator "A2L File generated by A2L Generator"')
    lines.append('  /begin MODULE A2LModule "Auto-generated Module"')
    
    # Add MOD_COMMON section
    lines.append('    /begin MOD_COMMON "Module common data"')
    lines.append('      MEMORY_LAYOUT RAM LONG 0x00000000 LONG 0xFFFFFFFF')
    lines.append('    /end MOD_COMMON')
    
    # Build COMPU_METHOD sections (if advanced mode or scaling factors exist)
    compu_methods = _build_compu_methods(elf_data, selected_symbols, advanced_mode)
    if compu_methods:
        lines.extend(compu_methods)
    
    # Build UNIT sections
    unit_methods = _build_units(elf_data, selected_symbols)
    if unit_methods:
        lines.extend(unit_methods)
    
    # Build MEASUREMENT sections for each symbol
    lines.append('    /begin MEASUREMENTS "Symbol Measurements"')
    measurement_lines = _build_measurements(elf_data, map_data, selected_symbols)
    lines.extend(measurement_lines)
    lines.append('    /end MEASUREMENTS')
    
    # Build CHARACTERISTIC sections if in advanced mode
    if advanced_mode:
        lines.append('    /begin CHARACTERISTICS "Symbol Characteristics"')
        char_lines = _build_characteristics(elf_data, map_data, selected_symbols, enums)
        lines.extend(char_lines)
        lines.append('    /end CHARACTERISTICS')
    
    lines.append('  /end MODULE')
    lines.append('/end PROJECT')
    
    body_text = '\n'.join(lines) + '\n'
    
    # Handle template if provided
    if template_path and os.path.exists(template_path):
        with open(template_path, 'r', encoding='utf-8') as f:
            template = f.read()
        
        # Try multiple placeholder patterns
        if '{{A2L_BODY}}' in template:
            final_text = template.replace('{{A2L_BODY}}', body_text)
        elif '{A2L_BODY}' in template:
            final_text = template.replace('{A2L_BODY}', body_text)
        elif '/begin MEASUREMENTS' in template:
            # Find insertion point and insert measurement data
            final_text = template
        else:
            # Append to template
            final_text = template.rstrip() + '\n\n' + body_text
    else:
        final_text = body_text
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(final_text)


def _build_compu_methods(elf_data, selected_symbols, advanced_mode):
    """Build COMPU_METHOD sections for scaling factors and enumerations."""
    lines = []
    added_methods = set()
    
    for symbol in selected_symbols:
        elf_info = elf_data.get(symbol, {})
        scaling = elf_info.get('scaling', 1.0)
        enum_ref = elf_info.get('enum')
        
        # Add scaling compu method if needed
        if scaling and scaling != 1.0 and advanced_mode:
            method_name = f'CM_SCALE_{symbol}'
            if method_name not in added_methods:
                lines.append(f'    /begin COMPU_METHOD {method_name} "Scaling for {symbol}"')
                lines.append('      CATEGORY LINEAR')
                lines.append(f'      COMPU_INTERNAL_TO_PHYS')
                lines.append(f'        COMPU_SCALES')
                lines.append(f'          /begin COMPU_SCALE 0 999999')
                lines.append(f'            LOWER_LIMIT 0')
                lines.append(f'            UPPER_LIMIT 999999')
                lines.append(f'            COMPU_RATIONAL_COEFFICIENTS')
                lines.append(f'              COEFFICIENTS 0 {scaling} 0 1 0 1')
                lines.append(f'            /end COMPU_RATIONAL_COEFFICIENTS')
                lines.append(f'          /end COMPU_SCALE')
                lines.append(f'        /end COMPU_SCALES')
                lines.append(f'      /end COMPU_INTERNAL_TO_PHYS')
                lines.append('    /end COMPU_METHOD')
                added_methods.add(method_name)
        
        # Add enum compu method if referenced
        if enum_ref and advanced_mode:
            method_name = f'CM_ENUM_{symbol}'
            if method_name not in added_methods:
                lines.append(f'    /begin COMPU_METHOD {method_name} "Enumeration for {symbol}"')
                lines.append('      CATEGORY ENUMERATION')
                lines.append('      COMPU_INTERNAL_TO_PHYS')
                lines.append('        COMPU_SCALES')
                # Add enum values if available
                lines.append('        /end COMPU_SCALES')
                lines.append('      /end COMPU_INTERNAL_TO_PHYS')
                lines.append('    /end COMPU_METHOD')
                added_methods.add(method_name)
    
    return lines


def _build_units(elf_data, selected_symbols):
    """Build UNIT sections for measurements."""
    lines = []
    added_units = set()
    
    for symbol in selected_symbols:
        elf_info = elf_data.get(symbol, {})
        dtype = elf_info.get('datatype', 'UBYTE')
        unit_name = f'UNIT_{symbol}'
        
        if unit_name not in added_units:
            lines.append(f'    /begin UNIT {unit_name} "{dtype} unit"')
            lines.append(f'      SI_UNIT')
            lines.append(f'      DISPLAY "{dtype}"')
            lines.append(f'    /end UNIT')
            added_units.add(unit_name)
    
    return lines


def _build_measurements(elf_data, map_data, selected_symbols):
    """Build MEASUREMENT sections with actual symbol data."""
    lines = []
    
    for symbol in sorted(selected_symbols):
        if symbol not in elf_data or symbol not in map_data:
            continue
        
        elf_info = elf_data[symbol]
        map_info = map_data[symbol]
        
        address = map_info.get('address', elf_info.get('address', 0))
        size = map_info.get('size', elf_info.get('size', 0))
        dtype = elf_info.get('datatype', 'UBYTE')
        scaling = elf_info.get('scaling', 1.0)
        
        lines.append(f'      /begin MEASUREMENT {symbol}')
        lines.append(f'        DESCRIPTION "{symbol} - Extracted from ELF/MAP"')
        lines.append(f'        ECU_ADDRESS 0x{address:08X}')
        lines.append(f'        DATA_SIZE {size}')
        lines.append(_get_a2l_datatype(dtype))
        
        if scaling and scaling != 1.0:
            lines.append(f'        COMPU_METHOD CM_SCALE_{symbol}')
        
        lines.append(f'      /end MEASUREMENT')
    
    return lines


def _build_characteristics(elf_data, map_data, selected_symbols, enums):
    """Build CHARACTERISTIC sections for advanced mode."""
    lines = []
    
    for symbol in sorted(selected_symbols):
        if symbol not in elf_data or symbol not in map_data:
            continue
        
        elf_info = elf_data[symbol]
        map_info = map_data[symbol]
        
        address = map_info.get('address', elf_info.get('address', 0))
        size = map_info.get('size', elf_info.get('size', 0))
        dtype = elf_info.get('datatype', 'UBYTE')
        
        lines.append(f'      /begin CHARACTERISTIC {symbol}')
        lines.append(f'        DESCRIPTION "{symbol} characteristic"')
        lines.append(f'        MEMORY_LOCATION RAM')
        lines.append(f'        ECU_ADDRESS 0x{address:08X}')
        lines.append(_get_a2l_datatype(dtype))
        lines.append(f'      /end CHARACTERISTIC')
    
    return lines


def _get_a2l_datatype(dtype):
    """Map Python/ELF datatype to ASAP2 datatype specification."""
    datatype_map = {
        'UBYTE': '        DATA_TYPE A_UBYTE',
        'BYTE': '        DATA_TYPE A_INT8',
        'UWORD': '        DATA_TYPE A_UINT16',
        'WORD': '        DATA_TYPE A_INT16',
        'ULONG': '        DATA_TYPE A_UINT32',
        'LONG': '        DATA_TYPE A_INT32',
        'FLOAT32_IEEE': '        DATA_TYPE A_FLOAT32_IEEE',
        'FLOAT64_IEEE': '        DATA_TYPE A_FLOAT64_IEEE',
    }
    return datatype_map.get(dtype, '        DATA_TYPE A_UBYTE')
